/*
 *  Student Number : 17260
 *  Student Name : Mirza Usman
 */
package mizarusman.userinterface;

/**
 *
 * @author user
 */
public class AdministratorDashboard extends javax.swing.JFrame {

    /**
     * Creates new form AdministratorLogin
     */
    public AdministratorDashboard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        lblAllStudents = new javax.swing.JLabel();
        lblNewCourse = new javax.swing.JLabel();
        lblNewStudent = new javax.swing.JLabel();
        lblFees = new javax.swing.JLabel();
        lblNewFaculty = new javax.swing.JLabel();
        lblNewTimetable = new javax.swing.JLabel();
        lblBanner = new javax.swing.JLabel();

        jButton1.setText("jButton1");

        lblAllStudents.setForeground(new java.awt.Color(0, 51, 255));
        lblAllStudents.setText("View Students");
        lblAllStudents.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblAllStudentsMouseClicked(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblNewCourse.setForeground(new java.awt.Color(0, 51, 255));
        lblNewCourse.setText("Create Course");
        lblNewCourse.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblNewCourseMouseClicked(evt);
            }
        });

        lblNewStudent.setForeground(new java.awt.Color(0, 51, 255));
        lblNewStudent.setText("Enroll Student");
        lblNewStudent.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblNewStudentMouseClicked(evt);
            }
        });

        lblFees.setForeground(new java.awt.Color(0, 51, 255));
        lblFees.setText("Fees Management");
        lblFees.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblFeesMouseClicked(evt);
            }
        });

        lblNewFaculty.setForeground(new java.awt.Color(0, 51, 255));
        lblNewFaculty.setText("Add Faculty Member");
        lblNewFaculty.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblNewFacultyMouseClicked(evt);
            }
        });

        lblNewTimetable.setForeground(new java.awt.Color(0, 51, 255));
        lblNewTimetable.setText("Add Timetable");

        lblBanner.setText("WELCOME TO YOUR ADMIN PANEL: ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblNewCourse)
                    .addComponent(lblNewStudent))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNewFaculty)
                    .addComponent(lblFees))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(lblNewTimetable)
                .addGap(64, 64, 64))
            .addGroup(layout.createSequentialGroup()
                .addGap(109, 109, 109)
                .addComponent(lblBanner)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addComponent(lblBanner)
                .addGap(79, 79, 79)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNewCourse)
                    .addComponent(lblNewFaculty)
                    .addComponent(lblNewTimetable))
                .addGap(68, 68, 68)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNewStudent)
                    .addComponent(lblFees))
                .addContainerGap(180, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblNewCourseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNewCourseMouseClicked
        new CreateCourse().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lblNewCourseMouseClicked

    private void lblNewFacultyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNewFacultyMouseClicked
        new RegisterFacultyMember().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lblNewFacultyMouseClicked

    private void lblNewStudentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNewStudentMouseClicked
        new StudentEnrollment().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lblNewStudentMouseClicked

    private void lblFeesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblFeesMouseClicked
         new FeesManagement().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lblFeesMouseClicked

    private void lblAllStudentsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAllStudentsMouseClicked
         new ViewStudents().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lblAllStudentsMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdministratorDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdministratorDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdministratorDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdministratorDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdministratorDashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel lblAllStudents;
    private javax.swing.JLabel lblBanner;
    private javax.swing.JLabel lblFees;
    private javax.swing.JLabel lblNewCourse;
    private javax.swing.JLabel lblNewFaculty;
    private javax.swing.JLabel lblNewStudent;
    private javax.swing.JLabel lblNewTimetable;
    // End of variables declaration//GEN-END:variables
}
